//*:
  code:
    standard: Symfony

//*.flv:
  code:

//*.gif:
  props:
    'svn:mime-type': image/gif

//*.jpg:
  code:

//*.mpg:
  code:

//*.pdf:
  code:

//*.php:
  preamble:

//*.png:
  code:

//*.swf:
  code:

apps/*/i18n/*/messages.xml:
  code:

apps/*/modules/*/templates//*:
  code:

apps/*/templates//*:
  code:

apps/qubit/lib/export/*.xml:
  code:

apps/qubit/lib/xslt/*.xml:
  code:

apps/qubit/lib/xslt/*.xsl:
  code:

config/package.xml:
  code:

lib/GoogleMapAPI//*:
  code:



lib/model/map//*:
  code:

lib/model/om//*:
  code:

/lib/*/base//*:
  code:

/plugins/*Plugin/lib/*/base//*:
  code:

/plugins/*Plugin/lib/model/map//*:
  code:

/plugins/*Plugin/lib/model/om//*:
  code:




lib/model/doctrine/base//*:
  code:

lib/model/doctrine/*/base//*:
  code:

lib/form/doctrine/base//*:
  code:

lib/form/doctrine/*/base//*:
  code:
  
lib/filter/doctrine/base//*:
  code:

lib/filter/doctrine/*/base//*:
  code:










lib/vendor//*:
  code:

lib/xhtml-to-xslfo.xsl:
  code:

plugins/*/modules/*/templates//*:
  code:

plugins/*/package.xml:
  code:

plugins/sfAuditPlugin/lib/vendor//*:
  code:

plugins/sfThumbnailPlugin//*:
  code:

test/selenium//*:
  code:

web/vendor//*:
  code:
