//*:
  code:
    standard: Symfony

//*.flv:
  code:

//*.gif:
  props:
    'svn:mime-type': image/gif

//*.jpg:
  code:

//*.mpg:
  code:

//*.pdf:
  code:

//*.php:
  preamble:
  props:
    'svn:keywords': Author Id Revision
    'svn:eol-style': native

//*.png:
  code:
  props:
    'svn:mime-type': image/png

//*.swf:
  code:

apps/*/i18n/*/messages.xml:
  code:

apps/*/modules/*/templates//*:
  code:

apps/*/templates//*:
  code:

apps/qubit/lib/export/*.xml:
  code:

apps/qubit/lib/xslt/*.xml:
  code:

apps/qubit/lib/xslt/*.xsl:
  code:

config/package.xml:
  code:

lib/GoogleMapAPI//*:
  code:

lib/model/map//*:
  code:

lib/model/om//*:
  code:

lib/vendor//*:
  code:
  props:

lib/xhtml-to-xslfo.xsl:
  code:

plugins/*/modules/*/templates//*:
  code:

plugins/*/package.xml:
  code:

plugins/sfAuditPlugin/lib/vendor//*:
  code:
  props:

plugins/sfThumbnailPlugin//*:
  code:
  props:

test/selenium//*:
  code:

web/vendor//*:
  code:
